# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.caching=false
org.gradle.configuration-cache=false
org.gradle.parallel=true
org.gradle.tooling.parallel=true
kotlin.code.style=official
kotlin.incremental=true

android.useAndroidX=true
android.enableJetifier=false
android.nonTransitiveRClass=true
realtynova.api.key=d8fcff6a8a2448dd873beac635ecf578
maps.api.key=AIzaSyB_078J3na7VP2p1SbhC-fD0lJq3C536nw
android.builtInKotlin=false
android.newDsl=false
