package com.denis.realtynova.features.messages

import androidx.lifecycle.SavedStateHandle
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.denis.realtynova.core.domain.model.Message
import com.denis.realtynova.core.domain.model.User
import com.denis.realtynova.core.domain.repository.AuthRepository
import com.denis.realtynova.core.domain.repository.ChatRepository
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.*
import kotlinx.coroutines.launch
import javax.inject.Inject

sealed interface ChatUiState {
    data object Loading : ChatUiState
    data class Success(
        val messages: List<Message>,
        val currentUser: User?,
        val otherUserId: String,
        val isOtherUserTyping: Boolean = false
    ) : ChatUiState
    data class Error(val message: String) : ChatUiState
}

@HiltViewModel
class ChatDetailViewModel @Inject constructor(
    private val authRepository: AuthRepository,
    private val chatRepository: ChatRepository,
    savedStateHandle: SavedStateHandle
) : ViewModel() {
    
    private val otherUserId: String = checkNotNull(savedStateHandle["userId"])
    
    private val _uiState = MutableStateFlow<ChatUiState>(ChatUiState.Loading)
    val uiState: StateFlow<ChatUiState> = _uiState.asStateFlow()

    init {
        loadMessages()
    }

    private fun loadMessages() {
        viewModelScope.launch {
            val currentUser = authRepository.currentUser.first()
            if (currentUser == null) {
                _uiState.value = ChatUiState.Error("User not logged in")
                return@launch
            }
            
            val chatId = chatRepository.createChatId(currentUser.id, otherUserId)
            
            // Collect typing status
            launch {
                chatRepository.getTypingStatus(chatId, otherUserId).collect { isTyping ->
                    val currentState = _uiState.value
                    if (currentState is ChatUiState.Success) {
                        _uiState.value = currentState.copy(isOtherUserTyping = isTyping)
                    }
                }
            }

            chatRepository.getMessages(chatId)
                .onStart { _uiState.value = ChatUiState.Loading }
                .catch { e -> _uiState.value = ChatUiState.Error(e.message ?: "Unknown error") }
                .collect { messages ->
                    val currentState = _uiState.value
                    if (currentState is ChatUiState.Success) {
                        _uiState.value = currentState.copy(messages = messages, currentUser = currentUser)
                    } else {
                        _uiState.value = ChatUiState.Success(messages, currentUser, otherUserId)
                    }
                }
        }
    }

    fun setTyping(isTyping: Boolean) {
        val currentUser = (uiState.value as? ChatUiState.Success)?.currentUser ?: return
        viewModelScope.launch {
            val chatId = chatRepository.createChatId(currentUser.id, otherUserId)
            chatRepository.setTypingStatus(chatId, currentUser.id, isTyping)
        }
    }

    fun sendMessage(content: String) {
        val currentState = uiState.value as? ChatUiState.Success ?: return
        val currentUser = currentState.currentUser ?: return
        
        viewModelScope.launch {
            val message = Message(
                id = "", // Will be generated by Repository
                senderId = currentUser.id,
                receiverId = otherUserId,
                content = content
            )
            val chatId = chatRepository.createChatId(currentUser.id, otherUserId)
            chatRepository.sendMessage(chatId, message)
        }
    }
}
