type User @table {
  email: String!
  role: String!
  createdAt: Timestamp!
  fullName: String
  phoneNumber: String
  isVerifiedAgent: Boolean
}

type Listing @table {
  title: String!
  price: Float!
  listingType: String!
  county: String!
  neighborhood: String!
  propertyType: String!
  description: String
  amenities: [String]
  imageUrls: [String]
  latitude: Float
  longitude: Float
  embedding: Vector @col(size: 768)
  agent: User!
}

type Favorite @table {
  user: User!
  listing: Listing!
}

type VisitRequest @table {
  requestedDate: Timestamp!
  status: String!
  notes: String
  seeker: User!
  listing: Listing!
}

type Review @table {
  rating: Int!
  comment: String!
  createdAt: Timestamp!
  reviewer: User!
  agent: User!
}